"""empty message

Revision ID: 73e8a95c21f3
Revises: 5b74e6ff4948
Create Date: 2024-09-03 13:30:15.125499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '73e8a95c21f3'
down_revision: Union[str, None] = '5b74e6ff4948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessagemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatmessagemodel')
    # ### end Alembic commands ###
