"""empty message

Revision ID: 974bc85deb53
Revises: 73e8a95c21f3
Create Date: 2024-09-03 13:33:32.868532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '974bc85deb53'
down_revision: Union[str, None] = '73e8a95c21f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
